### ISSUE TITLE
Unable to parse emails from yahoo mail

### ISSUE THREAD

**Issue by arunrreddy** [mat-sz/letterparser#3]
Getting the below error while parsing email from yahoo.

`TypeError: Cannot read property 'startsWith' of undefined
    at parseContentType (/home/arun/workspace/vidwaan-api/node_modules/letterparser/lib/parser.js:56:29)
    at Object.parseBody (/home/arun/workspace/vidwaan-api/node_modules/letterparser/lib/parser.js:136:22)
    at Object.parse (/home/arun/workspace/vidwaan-api/node_modules/letterparser/lib/index.js:32:30)`

**Comment by mat-sz** [comment]
Fixed in 1d8160262a523e73ac0904eeebe92f9a614a4444.

**Comment by mat-sz** [comment]
Published in version 0.0.5.
